#!/usr/bin/env node

import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);

const COMPLEX_ASSET_PATTERN =
  /(hero|portrait|avatar|mascot|character|illustration|photo|product|thumbnail|screenshot|project|banner|artwork)/i;
const SVG_GENERATOR_PATTERN =
  /(<svg[\s>]|svgWrap|sharp\s*\(\s*Buffer\.from\s*\(\s*svg|\.toFile\s*\(|canvas|getContext\s*\()/i;

function usage() {
  console.error(`Usage:
  node ${path.basename(__filename)} <react-project-dir>`);
}

function walk(dir, files = []) {
  if (!existsSync(dir)) return files;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name === "dist" || entry.name === ".git") continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, files);
    else files.push(full);
  }
  return files;
}

function collectReferencedAssets(projectDir) {
  const sourceFiles = walk(projectDir).filter((file) => /\.(jsx?|tsx?|css|html)$/.test(file));
  const assets = new Set();

  for (const file of sourceFiles) {
    const text = readFileSync(file, "utf8");
    const patterns = [
      /(?:src|href)=["'`]([^"'`]+\.(?:png|jpe?g|webp|gif|svg))["'`]/gi,
      /url\(["']?([^"')]+\.(?:png|jpe?g|webp|gif|svg))["']?\)/gi,
      /["'`]([^"'`]*(?:\/assets\/|assets\/)[^"'`]+\.(?:png|jpe?g|webp|gif|svg))["'`]/gi,
    ];

    for (const pattern of patterns) {
      for (const match of text.matchAll(pattern)) {
        const ref = match[1];
        if (/^(https?:)?\/\//i.test(ref) || ref.startsWith("data:")) continue;
        assets.add(ref);
      }
    }
  }

  return [...assets];
}

function resolveAsset(projectDir, ref) {
  const cleanRef = ref.split(/[?#]/)[0];
  const candidates = [];

  if (cleanRef.startsWith("/")) {
    candidates.push(path.join(projectDir, "public", cleanRef));
    candidates.push(path.join(projectDir, cleanRef.slice(1)));
  } else {
    candidates.push(path.join(projectDir, cleanRef));
    candidates.push(path.join(projectDir, "public", cleanRef));
    candidates.push(path.join(projectDir, "src", cleanRef));
  }

  return candidates.find((candidate) => existsSync(candidate));
}

function collectGeneratorHits(projectDir) {
  const scriptDirs = [path.join(projectDir, "scripts"), path.join(projectDir, "tools")];
  const files = scriptDirs.flatMap((dir) => walk(dir)).filter((file) => /\.(mjs|cjs|js|ts)$/.test(file));
  const hits = new Map();

  for (const file of files) {
    const text = readFileSync(file, "utf8");
    if (!SVG_GENERATOR_PATTERN.test(text)) continue;

    for (const match of text.matchAll(/["'`]([^"'`]+\.(?:png|jpe?g|webp))["'`]/gi)) {
      const filename = path.basename(match[1]);
      if (!COMPLEX_ASSET_PATTERN.test(filename)) continue;
      if (!hits.has(filename)) hits.set(filename, []);
      hits.get(filename).push(file);
    }
  }

  return hits;
}

const projectDir = process.argv[2] ? path.resolve(process.argv[2]) : null;
if (!projectDir || !existsSync(projectDir)) {
  usage();
  process.exit(2);
}

const referencedAssets = collectReferencedAssets(projectDir);
const generatorHits = collectGeneratorHits(projectDir);
const failures = [];

for (const ref of referencedAssets) {
  const resolved = resolveAsset(projectDir, ref);
  const filename = path.basename(ref);

  if (!resolved) {
    failures.push(`Missing referenced image asset: ${ref}`);
    continue;
  }

  const size = statSync(resolved).size;
  if (size === 0) {
    failures.push(`Empty image asset: ${resolved}`);
  }

  if (COMPLEX_ASSET_PATTERN.test(filename) && generatorHits.has(filename)) {
    const scripts = [...new Set(generatorHits.get(filename))].map((file) => path.relative(projectDir, file));
    failures.push(
      `Complex image asset "${filename}" appears to be generated by SVG/shape code in ${scripts.join(", ")}. Use a screenshot crop, user-supplied file, or image generation output instead.`,
    );
  }
}

if (failures.length > 0) {
  console.error("Visual asset audit failed:");
  for (const failure of failures) console.error(`- ${failure}`);
  process.exit(1);
}

console.log(`Visual asset audit passed: ${referencedAssets.length} referenced image asset(s) checked.`);
